# `digest_algorithm` allow md5, sha1, sha256 (sha2-256), sha512 (sha2-512) as parameter.
digest_algorithm: "sha2-256"
manifest_client_local: ".minecraft/mods/"
manifest_remote_url: "https://www.ourorangenet.com/download/caji_server/mods"